sudo: required
services:
  - docker

before_install:
  - docker build -t h3llr4iser/docker-nuxt -f ./web/Dockerfile.dev .

script:
  - docker run h3llr4iser/docker-nuxt yarn test

after_success:
  - docker build -t h3llr4iser/nuxt-web ./web
  - docker build -t h3llr4iser/nuxt-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push h3llr4iser/nuxt-web
  - docker push h3llr4iser/nuxt-nginx
 

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-nuxt"
  env: "DockerNuxt-env"
  bucket_name: "elasticbeanstalk-eu-west-1-725101668907"
  bucket_path: "docker-nuxt"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"