version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - /myapp/node_modules
      - .:/myapp
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes: 
      - /myapp/node_modules
      - .:/myapp    
    command: ["yarn", "watch:test"]