version: '3'
services:
  client:
    build: 
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app
  tests:
    build: 
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes: 
      - /app/node_modules
      - .:/app    
    command: ["yarn", "watch:test"]
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "81:80"    